apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-depl
spec:
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: apache:2.4
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/bash
                - -c
                - |
                  echo "<html><body><h1>Welcome to the Web App</h1></body></html>" > /usr/local/apache2/htdocs/index.html

        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
